application: metapoems
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: static_files/css
- url: /js
  static_dir: static_files/js

- url: /.*
<<<<<<< HEAD
  script: main.app

=======
  script: main.app 
    
>>>>>>> 5456a0bd151fb60ef13e5b62cd8fd4685d9aaa90
libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest