application: metapoems
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: static_files/css
- url: /js
  static_dir: static_files/js
- url: /img
  static_dir: static_files/authorPictures
- url: /corpus
  static_dir: static_files/corpus

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest